######################## default configuration ####################
baseURL = "/"
languageCode = "en"
title = "Home"
theme = "hugo-strata-theme"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/vendor/ecicons.min.css"
  [[params.plugins.css]]
  link = "css/variables.css"

  [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/animate.css"
  [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/swiper-bundle.min.css"
    [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/jquery-ui.min.css"
    [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/countdownTimer.css"
  [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/slick.min.css"
    [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/plugins/bootstrap.css"

      [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/style.css"

  [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/responsive.css"
    [[params.plugins.css]]
  link = "https://v1.eralive.net/assets/css/backgrounds/bg-4.css"
  

  # JS Plugins

  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/popper.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/bootstrap.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/jquery-migrate-3.3.0.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/modernizr-3.11.2.min.js"


    [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/swiper-bundle.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/countdownTimer.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/scrollup.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/jquery.zoom.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/slick.min.js"
  
      [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/infiniteslidev2.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/plugins/jquery.sticky-sidebar.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/vendor/index.js"
  [[params.plugins.js]]
  link = "https://v1.eralive.net/assets/js/main.js"




    [[params.plugins.js]]
  link = "javascript/config.js"
  [[params.plugins.js]]
  link = "https://controllers.eralive.net/v1/routes/web.js"



############################## navigation ###############################
[menu]



  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  [[menu.main]]
  name = "Dashboard"
  URL = "dashboard"
  weight = 4
  
  
  [[menu.main]]
  name = "Tracker"
  URL = "tracker"
  weight = 4


  ############# footer menu #############
   [[menu.footer]]
  name = "Home"
  URL = "/"
  weight = 1



  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
invoice = "images/invoice.png"
home = "Home"
# Meta data
description = "This is meta description"
category = ""
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
# mobile = "0124857985320"
# email = "demo@email.com"
# location = "Dhaka, Bangladedsh"
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"

currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "eci-facebook"
  link = "#"
  id= "facebook"
  itemid= "itemfb"

  [[params.social]]
  icon = "eci-twitter"
  link = "#"
  id= "twitter"
  itemid= "itemtw"

  [[params.social]]
  icon = "eci-youtube"
  link = "#"
  id= "youtube"
  itemid= "itemyt"

  [[params.social]]
  icon = "eci-instagram"
  link = "#"
  id= "instagram"
  itemid= "iteminta"
  
  [[params.social]]
  icon = "eci-pinterest"
  link = "#"
  id= "pinterest"
  itemid= "itempt"



  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
